import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";
import { withSerwist } from "@serwist/turbopack";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const nextConfig: NextConfig = {
    // React Compiler: on in production, opt-in in dev via env var
    reactCompiler: process.env.NODE_ENV === "production" || process.env.REACT_COMPILER === "true",
    poweredByHeader: false,
    compress: true,
    experimental: {
        // Tree-shake heavy packages to reduce client bundle
        optimizePackageImports: ["framer-motion"],
    },
    async redirects() {
        return [
            { source: "/scale",               destination: "/monster-scaler",       permanent: true },
            { source: "/scale/docs",          destination: "/monster-scaler/docs",  permanent: true },
            { source: "/balance",             destination: "/encounter-builder",    permanent: true },
            { source: "/balance/docs",        destination: "/encounter-builder/docs", permanent: true },
            { source: "/items",               destination: "/artifact-forge",       permanent: true },
            { source: "/items/docs",          destination: "/artifact-forge/docs",  permanent: true },
            { source: "/encounters-en-route", destination: "/travel-encounters",    permanent: true },
        ];
    },
    async headers() {
        // These public/ assets are unhashed (no content fingerprint in the
        // filename, unlike /_next/static/*, which Next.js already caches
        // immutably by default), so nothing was telling browsers/CDNs how
        // long to keep them — flagged by PageSpeed Insights as "Use
        // efficient cache lifetimes". They're static branding assets that
        // effectively never change in place (a real content change would
        // ship under a new filename), so a long cache is safe. manifest.json
        // gets a shorter lifetime since its content (e.g. shortcuts) is more
        // likely to change without a filename bump.
        const longCache = "public, max-age=31536000, immutable";
        return [
            {
                source: "/icons/:path*",
                headers: [{ key: "Cache-Control", value: longCache }],
            },
            {
                source: "/:file(crealizr_favicon\\.svg|og-.*\\.svg)",
                headers: [{ key: "Cache-Control", value: longCache }],
            },
            {
                source: "/manifest.json",
                headers: [{ key: "Cache-Control", value: "public, max-age=86400" }],
            },
        ];
    },
};

// The service worker itself is compiled by the route handler at
// src/app/sw.js/[[...path]]/route.ts via @serwist/turbopack, which is the
// only Serwist package with real Turbopack support — both next-pwa and the
// standard @serwist/next package hook into webpack config directly, which
// this app's Turbopack build (Next.js 16's default) never runs, so sw.js
// was silently never generated by any prior build or deploy.
export default withSerwist(withNextIntl(nextConfig));
