import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";
import { withSerwist } from "@serwist/turbopack";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const nextConfig: NextConfig = {
    // React Compiler: on in production, opt-in in dev via env var
    reactCompiler: process.env.NODE_ENV === "production" || process.env.REACT_COMPILER === "true",
    poweredByHeader: false,
    compress: true,
    experimental: {
        // Tree-shake heavy packages to reduce client bundle
        optimizePackageImports: ["framer-motion"],
    },
    async redirects() {
        return [
            { source: "/scale",               destination: "/monster-scaler",       permanent: true },
            { source: "/scale/docs",          destination: "/monster-scaler/docs",  permanent: true },
            { source: "/balance",             destination: "/encounter-builder",    permanent: true },
            { source: "/balance/docs",        destination: "/encounter-builder/docs", permanent: true },
            { source: "/items",               destination: "/artifact-forge",       permanent: true },
            { source: "/items/docs",          destination: "/artifact-forge/docs",  permanent: true },
            { source: "/encounters-en-route", destination: "/travel-encounters",    permanent: true },
        ];
    },
};

// The service worker itself is compiled by the route handler at
// src/app/sw.js/[[...path]]/route.ts via @serwist/turbopack, which is the
// only Serwist package with real Turbopack support — both next-pwa and the
// standard @serwist/next package hook into webpack config directly, which
// this app's Turbopack build (Next.js 16's default) never runs, so sw.js
// was silently never generated by any prior build or deploy.
export default withSerwist(withNextIntl(nextConfig));
