export const metadata = {
  title: "Magic Item Creator – How it works",
  description: "Details on rarity by level, suggested bonuses, and the item blueprint produced by CRializr.",
};

function Code({ children }: { children: React.ReactNode }) {
  return <code className="rounded bg-black/40 px-1 py-0.5 text-amber-300">{children}</code>;
}

export default function ItemsDocsPage() {
  return (
    <section className="prose prose-invert max-w-3xl px-4 py-8">
      <h1 className="mb-2 text-3xl font-semibold">Magic Item Creator – How it works</h1>
      <p className="text-zinc-400">This page explains the simplified heuristics used to generate a balanced item blueprint tuned to a party level.</p>

      <h2 className="mt-8 text-xl font-semibold">Inputs</h2>
      <ul>
        <li>Item name (optional)</li>
        <li>Item type: <Code>Weapon</Code> | <Code>Armor</Code> | <Code>Wand</Code> | <Code>Wondrous</Code></li>
        <li>Player level (1–20) used for tuning</li>
        <li>Player Attunement Requirement setup</li>
        <li>Optional target monster tags to annotate effectiveness</li>
      </ul>

      <h2 className="mt-8 text-xl font-semibold">Rarity by level</h2>
      <p>Rarity is assigned from player level via a simple curve:</p>
      <ul>
        <li>≤3 → <Code>Common</Code></li>
        <li>4–6 → <Code>Uncommon</Code></li>
        <li>7–10 → <Code>Rare</Code></li>
        <li>11–16 → <Code>Very Rare</Code></li>
        <li>17–20 → <Code>Legendary</Code></li>
      </ul>

      <h2 className="mt-8 text-xl font-semibold">Suggested bonuses</h2>
      <p>Bonuses are intentionally conservative and scale softly by level tier:</p>
      <ul>
        <li>Tier: <Code>tier = clamp(1, 5, ceil(level / 4))</Code></li>
        <li>Bonus: <Code>bonus = min(3, floor((tier - 1)/2) + (level ≥ 17 ? 1 : 0))</Code> → ranges 0..3</li>
        <li>Avg damage bonus: <Code>avgDamage = max(0, tier - 1)</Code> → ranges 0..4</li>
        <li>Save DC (for wands): <Code>saveDC = 12 + tier</Code> → 13..17</li>
      </ul>
      <p>Application by type:</p>
      <ul>
        <li><Code>Weapon</Code>: <Code>bonusToHit = bonus</Code>, <Code>avgDamageBonus = avgDamage</Code></li>
        <li><Code>Armor</Code>: <Code>bonusAC = bonus</Code></li>
        <li><Code>Wand</Code>: <Code>bonusToHit = bonus</Code>, <Code>avgDamageBonus = avgDamage</Code>, <Code>bonusSaveDC = saveDC</Code></li>
        <li><Code>Wondrous</Code>: no automatic combat bonus (freeform design)</li>
      </ul>

      <h2 className="mt-8 text-xl font-semibold">Item blueprint</h2>
      <p>The tool returns a structured blueprint object you can export or copy:</p>
      <ul>
        <li><Code>name</Code>: provided or autogenerated from type and rarity</li>
        <li><Code>type</Code>: one of the supported types</li>
        <li><Code>attunement</Code>: boolean value (true/false)</li>
        <li><Code>rarity</Code>: derived from level</li>
        <li><Code>levelTuned</Code>: clamped level (1–20)</li>
        <li><Code>targetTags</Code>: your optional list</li>
        <li><Code>bonusToHit</Code>, <Code>bonusAC</Code>, <Code>bonusSaveDC</Code>, <Code>avgDamageBonus</Code>: as applicable</li>
        <li><Code>notes</Code>: summary text if targets were provided</li>
      </ul>

      <p className="mt-8 text-sm text-zinc-500">These are baseline heuristics for quick prep on mobile. Adjust or extend to fit your table’s tone.</p>
    </section>
  );
}
